import styles from './about.module.css'
import { Suspense } from 'react'
import Loading from './loading'

export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

export default function AboutLayout({ children }) {
  return (
    <>
    <div className={styles.main}>
        <Suspense fallback={<Loading />}>
        {children}
        </Suspense>        
        </div>
    </>
  )
}
